# Generated by Django 4.2.18 on 2025-01-30 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lyric_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lyric',
            options={'ordering': ['-created_at']},
        ),
    ]
