# Generated by Django 4.2.18 on 2025-02-06 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lyric_app', '0002_alter_genre_id_alter_lyric_id_alter_postapproval_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lyric',
            name='admin_accept',
        ),
        migrations.RemoveField(
            model_name='lyric',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='lyric',
            name='is_protected',
        ),
        migrations.DeleteModel(
            name='PostApproval',
        ),
    ]
