# Generated by Django 4.2.18 on 2025-01-31 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyric_app', '0003_postapproval'),
    ]

    operations = [
        migrations.AddField(
            model_name='lyric',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lyric',
            name='is_protected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lyric',
            name='status',
            field=models.IntegerField(choices=[(0, 'Personal'), (1, 'Published')], default=0),
        ),
        migrations.AlterField(
            model_name='postapproval',
            name='status',
            field=models.IntegerField(choices=[(0, 'Personal'), (1, 'Published')], default=0),
        ),
    ]
