# Generated by Django 4.2.18 on 2025-02-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyric_app', '0003_remove_lyric_admin_accept_remove_lyric_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lyric',
            name='admin_accept',
            field=models.BooleanField(default=False),
        ),
    ]
