# Generated by Django 4.2.18 on 2025-02-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyric_app', '0004_lyric_is_approved_lyric_is_protected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lyric',
            name='admin_accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lyric',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published'), (2, 'Awaiting Approval')], default=0),
        ),
        migrations.AlterField(
            model_name='postapproval',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published'), (2, 'Awaiting Approval')], default=0),
        ),
    ]
