# Generated by Django 4.2.18 on 2025-02-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyric_app', '0006_remove_lyric_admin_accept_alter_lyric_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lyric',
            name='genre_select',
            field=models.IntegerField(choices=[(0, 'Rap'), (1, 'Song'), (2, 'Poem'), (3, 'Other')], default=0),
        ),
        migrations.AlterField(
            model_name='lyric',
            name='status',
            field=models.IntegerField(choices=[(0, 'Personal'), (1, 'Submit for Publishing')], default=0),
        ),
        migrations.AlterField(
            model_name='postapproval',
            name='status',
            field=models.IntegerField(choices=[(0, 'Personal'), (1, 'Submit for Publishing')], default=0),
        ),
    ]
